### ISSUE TITLE
rpc not working with tauri app

### ISSUE THREAD

**Issue by jodev7** [jewlexx/discord-presence#19]
when i put tauri func to top rpc not working but when i put tauri func after rpc Discrod RpC working but tauri app not starting

![Screenshot 2022-09-30 142205](https://user-images.githubusercontent.com/80722162/193238618-7d097881-a3a9-4bd3-b9f3-b58f799486e2.png)

**Comment by jewlexx** [comment]
As far as I know the Tauri run function is blocking, so any code after that will not be run while the app is open.

This may be the same as the run function for drpc, though that is not meant to be the case. Could you try putting the rpc code in a seperate thread and see if both run in that case?

**Comment by jewlexx** [comment]
Also please in future use the Bug Report template.

For now please add the required information from the template.

**Comment by jewlexx** [comment]
Should be fixed in #20 :)
