### ISSUE TITLE
[FEATURE] Internal rate limiter

### ISSUE THREAD

**Issue by jewlexx** [jewlexx/discord-presence#23]
**Is your feature request related to a problem? Please describe.**
Internal rate limiter, to prevent devs from hitting Discord rate limits by default.

**Describe the solution you'd like. Also mention of you would be able to get involved in implementing the solution**
Implement a rate limiter that follows the Discord rate limit and only runs executions when the rate limit is refreshed.

**Comment by isitreallyalive** [comment]
I'll have a shot at this because I think it would be a nice to have.
