### ISSUE TITLE
`set_activity` runs before `start` despite being written after

### ISSUE THREAD

**Issue by valentinegb** [jewlexx/discord-presence#37]
Pretty sure I'm just doing something wrong here, but I can't figure out why `set_activity` runs before `start` in my program.

```rs
use discord_presence::Client;

fn main() {
    let mut client = Client::new(1066249445282422784);

    client.on_ready(|_| println!("Ready"));

    client.on_error(|ctx| eprintln!("{}", ctx.event));

    let thread = client.start();

    if let Err(err) = client.set_activity(|act| act.state("State Text")) {
        eprintln!("{}", err);
    }

    thread.join().unwrap()
}
```

This outputs the following:

```
Connection has not been started
Ready
```

If someone could please explain to me what I'm doing wrong, I would greatly appreciate it!

**Comment by jewlexx** [comment]
`client.start` runs asynchronously, hence the thread return. I really really want to figure out a better way to do this but as of now that is how it works.
So therefore `client.set_activity` is being run before the `Ready` event fires. You can await this event either by blocking or through callbacks, and this is the intended way to set activity at startup.
