### ISSUE TITLE
[FEATURE] Button support in activities

### ISSUE THREAD

**Issue by Tofixrs** [jewlexx/discord-presence#38]
I just want support for these in activities 
![Screenshot_2023-01-24-21-11-36_1920x1080](https://user-images.githubusercontent.com/73693639/214398630-ac893356-24be-476a-8028-6d4a91a04393.png)

**Comment by jewlexx** [comment]
I can't seem to find documentation from Discord on custom buttons in activity. I can only find [Ask to join](https://discord.com/developers/docs/rich-presence/how-to#ask-to-join) and [Spectate](https://discord.com/developers/docs/rich-presence/how-to#spectating).
Do you have a link to the docs for implementing something like this?

**Comment by lewisfm** [comment]
Here's an implementation that has buttons: https://github.com/discordjs/RPC. Could possibly be helpful.

**Comment by lewisfm** [comment]
As for documentation: the API describes the [`SET_ACTIVITY` command](https://discord.com/developers/docs/topics/rpc#setactivity) as having an [Activity object](https://discord.com/developers/docs/topics/gateway-events#activity-object), which contains a list of [Activity Buttons](https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-buttons).

**Comment by jewlexx** [comment]
Ah awesome thank you very much

**Comment by LukePrior** [comment]
Any update on this?

**Comment by jewlexx** [comment]
I haven't had much time to work on this recently, but it is on my roadmap once I have a bit more time.
