### ISSUE TITLE
[FEATURE] Removing event handlers

### ISSUE THREAD

**Issue by lewisfm** [jewlexx/discord-presence#40]
**Is your feature request related to a problem? Please describe.**
Right now it doesn't look like it's possible to remove event handlers. This is unfortunate, because it means registering an event handler is always a memory leak.

**Describe the solution you'd like. Also mention of you would be able to get involved in implementing the solution**
Ideally the `on_event` method would return a value that de-registers the event callback when it is dropped. The old behavior could be restored by using `std::mem::forget` on the returned value.

**Describe alternatives you've considered**
Another option would be to have some sort of `delete_handler` or `remove_event_handler` method on the Client. This has the downside of allowing you to try and deregister a listener multiple times or deregister one that doesn't exist, making some kind of runtime error.

**Comment by lewisfm** [comment]
I've made a fork that has this functionality (i updated the examples and added tests too), but it's a pretty breaking change so i'm not totally sure if you'll want a pull request for it. let me know if it looks good though. https://github.com/doinkythederp/discord-presence/tree/unregister-events

**Comment by lewisfm** [comment]
Here's an example of what this would look like:
```rs
// this listener lasts the entire program so it's only deregistered once the client goes out of scope
let _ready = client.on_ready(|_ctx| {
    println!("READY!");
});

{
    // this listener only lasts until the sleep function finishes
    let _ready_first_3_seconds = client.on_ready(|_ctx| {
        println!("READY, IN THE FIRST 3 SECONDS!");
    });
    sleep(Duration::from_secs(3));
}

{
    // this listener's Drop impl is skipped so it's only deregistered
    // once the client goes out of scope
    let error = client.on_error(|_ctx| {
        println!("ERROR!");
    });
    std::mem::forget(error);
}
```

**Comment by jewlexx** [comment]
Hey sorry for the inactivity, would you like to open a PR?
