### ISSUE TITLE
[FEATURE] Check ready status without event listener

### ISSUE THREAD

**Issue by fucksophie** [jewlexx/discord-presence#50]
**Is your feature request related to a problem? Please describe.**
There is no consise and easy way to get the ready status of the RPC without using an event listener.

**Describe the solution you'd like. Also mention of you would be able to get involved in implementing the solution**
the `READY` AtomicBool to be un-privated.

**Describe alternatives you've considered**
Using a event listener, but I couldn't move refs around properly and it didn't seem to work that well. This seems like a built-in thing which would be easier to use.

**Comment by jewlexx** [comment]
When I'm back at my computer I'll add a way to check without the event listener. I don't think that un-privating the AtomicBool would work though as if the user changed it that could break the library internally.
