### ISSUE TITLE
Failed to connect: IoError(Custom { kind: TimedOut, error: "timed out while reading from pipe" })

### ISSUE THREAD

**Issue by zibertszn** [jewlexx/discord-presence#57]
i'm run code from examples but it fails.
![image](https://github.com/jewlexx/discord-presence/assets/72556979/5a7a1844-31fa-4dee-a26c-d56d5e4878f2)

OS: Windows 11
Library version: 0.5.9

**Comment by jewlexx** [comment]
Did you ever figure out what caused this issue?
