### ISSUE TITLE
[FEATURE] Close/Exit/Quit

### ISSUE THREAD

**Issue by ShayBox** [jewlexx/discord-presence#58]
I need a way to close/exit/quit the thread, I just need the first ready event to get the user's discord id

```rust
impl Default for Ravenwood {
    fn default() -> Self {
        println!("[Ravenwood] Attempting to get your Discord ID using RPC");

        let client = Client::new();
        let mut discord_id = USER_ID;
        let mut discord_rpc = DiscordRPC::new(CLIENT_ID);
        discord_rpc.on_ready(|ctx| {
            let a = ctx.event;
            let b = a.as_object();
        });
        let handle = discord_rpc.start();
        // std::thread::sleep(Duration::from_secs(15));
        discord_rpc.block_until_event(Event::Ready).unwrap();

        if discord_id == USER_ID {
            println!("[Ravenwood] Couldn't get your Discord ID, please make sure Discord is open");
            println!("[Ravenwood] Defaulting to the ID of the developer of this program, ShayBox");
        }

        Self { client, discord_id }
    }
}
```

Letting the variables drop out of scope just causes the thread to crash when it receives an event  
Also, A model struct for the ready event would be nice

Maybe this can be done using Abortable  
https://docs.rs/futures/latest/futures/future/struct.Abortable.html

**Comment by jewlexx** [comment]
Dropping the variables should close the thread, but maybe that's not working properly. I'll see what I can do once I'm home.

Sorry for the late response

**Comment by ShayBox** [comment]
I just found that using `let _ = client.on_ready` will cause it to never emit a ready event, you must use persist or forget, that should be removed from the examples.
