### ISSUE TITLE
[BUG] Connection errors are not surfaced

### ISSUE THREAD

**Issue by JakeStanger** [jewlexx/discord-presence#62]
**Describe the bug**
If Discord is not running, or closes while the connection is open, an error is logged:

```
ERROR discord_presence::connection::manager: Failed to connect: IoError(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })
```

The connection manager then breaks from the send/receive loop, but the error itself is not propagated to the consumer, making it very difficult (or impossible) to actually detect and handle these situations (unless I'm missing something).

**To Reproduce**

1. Close discord
2. Run the following code:

```rs
let client = DiscordClient::new("id");

client.on_ready(|_| println!("ready"));
client.on_error(|err| println!("error: {err:?}"));

client.start();
````
3. Observe the above error printed from the library, but not captured by `on_error`.

**Expected behavior**
These connection errors should be propagated to the client's `on_error` handler, making it possible to capture and handle. It should be possible to capture connection errors when the library first starts, and at any point thereafter.

**Desktop (please complete the following information):**

- OS: Linux
- Version 0.5.16

**Comment by jewlexx** [comment]
Thanks for raising this, I'll have a look ASAP.
