### ISSUE TITLE
Use the Discord GameSDK

### ISSUE THREAD

**Issue by jewlexx** [jewlexx/discord-presence#69]
The [Discord GameSDK](https://discord.com/developers/docs/game-sdk/sdk-starter-guide) theoretically provides an easier way to interface with Discord RPC, without interacting with system pipes manually.

**Comment by lockieluke** [comment]
is this ever going to be implemented?

**Comment by jewlexx** [comment]
@lockieluke 
Realistically, no. 
The Discord GameSDK is closed source, and not licensed, meaning I cannot include it in the library directly.
As such, every single person who wanted to use the library would have to provide the SDK themselves, which, for many people, would be a dealbreaker.
I could obviously offer both options, but then I'm maintaining both for no reason, which just adds extra work, when I would be realistically better off just working on the custom implementation.
