### ISSUE TITLE
[BUG] Client::shutdown Err(NotStarted)

### ISSUE THREAD

**Issue by ShayBox** [jewlexx/discord-presence#94]
**Describe the bug**
When I call Client.shutdown() it returns an Err(NotStarted)  
I believe it's succeeding but still returning an Err, because if I use block_on instead, it doesn't error.

**To Reproduce**
```rust
lazy_static::lazy_static! {
    pub static ref USER: Option<PartialUser> = {
        let user_event = Arc::new(RwLock::new(None));
        let user_clone = user_event.clone();
        let mut client = Client::new(CLIENT_ID);

        client.on_ready(move |ctx| {
            if let EventData::Ready(event) = ctx.event {
                *user_event.write() = event.user;
            };
        }).persist();

        client.start();

        // block_until_event will never timeout
        std::thread::sleep(Duration::from_secs(5));

        client.shutdown().expect("Failed to stop RPC thread");

        let user = user_clone.read();

        user.clone()
    };
}
```

**Expected behavior**
Client.shutdown() to return Ok if it successfully shut down the thread.

**Screenshots**
![image](https://github.com/jewlexx/discord-presence/assets/9505196/339f6f70-6dfa-4492-be52-df9bb0545007)

**Desktop:**
- OS: Windows 11 23H2
- Version 1.1.0

**Comment by jewlexx** [comment]
Hey, looking into this now, I can recreate the issue locally, but for some reason, the blocking example works fine.

One thing I will point out is that it is generally better to use `client.block_until_event` instead of the thread sleeping unless you have a specific reason for using a hardcoded time.

That function doesn't timeout because Discord has somewhat harsh rate limits, and the intended behaviour is to just wait until those are refreshed.

**Comment by ShayBox** [comment]
My reason for the timeout is that Discord might not be open, have RPC disabled, use a web browser, custom client, etc, and I need None in those cases.

In my testing the process has to be stopped for long enough between restarts for RPC to disconnect, if it starts again too quickly it won't re-emit ready, but it will work again after some time, but I don't need it for anything but ready.

**Comment by jewlexx** [comment]
I've found a fix and it'll be published ASAP.

Thanks for the bug report
