### ISSUE TITLE
[BUG] RPC continually attempts to connect while Discord is closed.

### ISSUE THREAD

**Issue by jewlexx** [jewlexx/discord-presence#95]

**Comment by thedtvn** [comment]
hmm  and some how it not work on windows

**Comment by LennyPhoenix** [comment]
Would a short sleep here work (`manager.rs`):

![image](https://github.com/jewlexx/discord-presence/assets/57148878/e94e828d-7c6a-4d50-9516-5e7b23c8ed24)

The problem I have is that [`mpd-discord-rpc`](https://github.com/JakeStanger/mpd-discord-rpc) runs as a user service on my machine, but if discord isn't running then the `discord-presence` crate gets stuck in an infinite loop and consumes a lot of CPU, and subsequently drains my battery pretty heavily.

**Comment by jewlexx** [comment]
@LennyPhoenix A timeout would help but I want to figure out how to get both a customisable timeout and a limit on the number of connections.
Most devs won't want it continually trying to connect for the duration of their program, even with a timeout.
