### ISSUE TITLE
[FEATURE] Set activity type? "Listening to ..."

### ISSUE THREAD

**Issue by nednoodlehead** [jewlexx/discord-presence#97]
I'm developing a music app, and I would really like the ability to have the discord status say "Listening to \<music application\>" or "Listening on \<music application\>". Just like spotify. Right now it says "Playing \<discord developer application name\>"

Is there any way to change this? Or is this somehow changed through the discord dev api? I've looked through the docs.rs page, and didn't find much...

**Comment by jewlexx** [comment]
You can't, the Discord API doesn't allow this at all.

That feature is pretty much only for Discord Bots and Spotify.
